// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VPA.Client.VisualStudio.Extension.VSIX
{
    internal sealed partial class Vsix
    {
        public const string Id = "VPA.Client.VisualStudio.Extension.VSIX.295d9916-0ea1-43bd-ab51-ec5187358a86";
        public const string Name = "VPA.Client.VisualStudio.Extension.VSIX";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Joep van 't Land";
        public const string Tags = "";
    }
}
